language: ruby
rvm:
  - 2.2.2

env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
