# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f0c3004e03cd0c9e6bc6d091d5b5290ad6ffa31c53538d886000b46afd047ef2840ebf03a08026eea500f9c2943ade8d6f315f00428937b0b56ce2bc960b8d7

test:
  secret_key_base: a9c78690de7700526d30bfbb63b08ed38b282f651369b271b9ac12eb2f1051ced27fc781b639ead5579bdf79f6b1129c550c0db2089f7867565c03a05cece1e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
